name: soden
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - pip=19.3.1=py37_0
  - pycparser=2.19=py_0
  - setuptools=42.0.2=py37_0
  - six=1.13.0=py37_0
  - wheel=0.33.6=py37_0
  - pip:
    - autograd==1.3
    - autograd-gamma==0.4.1
    - cached-property==1.5.2
    - chardet==4.0.0
    - cycler==0.10.0
    - feather-format==0.4.1
    - future==0.18.2
    - h5py==3.1.0
    - idna==2.10
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - lifelines==0.23.6
    - llvmlite==0.35.0
    - matplotlib==3.1.2
    - numba==0.52.0
    - pandas==0.25.3
    - pyarrow==2.0.0
    - pycox==0.2.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - requests==2.25.1
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - seaborn==0.9.0
    - sklearn==0.0
    - torchdiffeq==0.1.1
    - torchtuples==0.2.0
    - urllib3==1.26.2
    - mkl_fft
    - mkl
    - intel-openmp
    - readline
    - tk
    - torch
    - cffi
    - numpy
    - mkl-service
    - mkl_random

